"""Add groups and group_members

Revision ID: b863afb6a5e3
Revises: 5ffc588ea476
Create Date: 2026-08-28 16:10:17.957216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b863afb6a5e3'
down_revision: Union[str, Sequence[str], None] = '5ffc588ea476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
