"""Add document_url to courses

Revision ID: f3b1fe084aad
Revises: 159af5a2f250
Create Date: 2026-08-26 00:50:59.953191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b1fe084aad'
down_revision: Union[str, Sequence[str], None] = '159af5a2f250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'document_url')
    # ### end Alembic commands ###
